### ISSUE TITLE
Adios2 is a Python package

### ISSUE THREAD

**Issue by minrk** [conda-forge/fenics-dolfinx-feedstock#15]
Libdolfinx depends on adios2, which is currently only a python package. This means libdolfinx requires Python, missing much of the point of the split package. Adios2 should split into libadios2, then libdolfinx can depend on libadios2.

Question: does the Dolfinx Python then depend on the Adios2 Python?

**Comment by garth-wells** [comment]
The DOFLINx Python package does not depend on ADIOS2 Python.
